name: BUILD

on:
  push:
  # schedule:
  #   - cron:  '1 */8 * * *'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [jdk17-openj9-bin, ffmpeg-amd-full]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: 检查包是否需要更新
      id: is-needed
      uses: ./check-is-needed
      with:
        package-name: ${{ matrix.repos }}

    
    - name: Paru 构建包
      uses: ./build-aur-action
      if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
      with:
        repo-name: ${{ matrix.repos }}
        preinstallPkgs: ${{ matrix.preinstall-pkgs }}
        makepkgProfilePath: ./makepkg.conf
    
    - uses: actions/upload-artifact@v3
      if: ${{ steps.is-needed.outputs.is-needed == 'true' }}
      with:
        path: ./*/*.pkg.tar.zst
        name: ${{ matrix.repos }}
        if-no-files-found: error
        
    # - uses: ncipollo/release-action@v1
    #   with:
    #     allowUpdates: true
    #     tag: "packages"
    #     artifacts: "./*/*.zst"
    #     token: ${{ secrets.GITHUB_TOKEN }}

  # buildNonAUR:
  #   strategy:
  #     matrix:
  #       PKGBUILDs: [linux-tikogasa-zen2]

  #     fail-fast: false
      
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Build Non-AUR packages
  #       id: makepkg
  #       uses: Pinghigh/pkgbuild-action@v5.1
  #       with:
  #         pkgdir: ${{ matrix.PKGBUILDs }}
  #         makepkgArgs: --skippgpcheck
          
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         path: ./*/*.pkg.tar.zst
  #         if-no-files-found: error
      
  #     # - uses: ncipollo/release-action@v1
  #     #   with:
  #     #     allowUpdates: true
  #     #     tag: "packages"
  #     #     artifacts: ${{ steps.makepkg.outputs.pkgfile0 }}
  #     #     token: ${{ secrets.GITHUB_TOKEN }}
      


  uploadToOneDrive:      
    runs-on: ubuntu-latest
    if: always()
    # needs: [buildNonAUR]
    needs: [buildAUR]

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/download-artifact@v3
        id: download
      - uses: ./create-db-and-upload-action
        with:
          RCLONE_ONEDRIVE_CLIENT_ID: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_ID }}
          RCLONE_ONEDRIVE_CLIENT_SECRET: ${{ secrets.RCLONE_ONEDRIVE_CLIENT_SECRET }}
          RCLONE_ONEDRIVE_REGION: global
          RCLONE_ONEDRIVE_TOKEN: ${{ secrets.RCLONE_ONEDRIVE_TOKEN }}
          RCLONE_ONEDRIVE_DRIVE_ID: ${{ secrets.RCLONE_ONEDRIVE_DRIVE_ID }}
          RCLONE_ONEDRIVE_DRIVE_TYPE: business
          dest_path: /repo-kogasa
          repo_name: repo-kogasa
          gpg-privatekey: ${{ secrets.GPG_PRIVATE_KEY }}
          local_path: ./
      
      
